apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopedge-app
  labels:
    app: shopedge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shopedge
  template:
    metadata:
      labels:
        app: shopedge
    spec:
      containers:
      - name: shopedge-app
        image: us-central1-docker.pkg.dev/PROJECT_ID/shopedgeedge/shopedge-app:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: shopedge-service
spec:
  selector:
    app: shopedge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopedge-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: shopedge-service
      port:
        number: 80